In [20]:
import numpy as np
# create array using numpy
#cretae 1D array
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim) # dimention
print(arr1.size) # size(no.of elements)
print(arr1.itemsize) # item size in bytes
print(arr1.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
1
4
8
int64


In [8]:
arr2=np.array([1,2,3,4])
arr2.reshape(1,4) # 1 row 5 columns

array([[1, 2, 3, 4]])

In [10]:
#2D array
arr3=np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [22]:
np.arange(0,10,2)
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4)) # creates 2D array with 3 rows, 4 columns and fill with 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])