In [4]:
import  numpy as np
# numpy vectorized operations
#for these operations shape of both the vectors should be same
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print("addition: ",arr1+arr2)
print("subtraction: ",arr1-arr2)
print("multiplication: ",arr1*arr2)
print("division: ",arr1/arr2)

addition:  [11 22 33 44 55]
subtraction:  [ -9 -18 -27 -36 -45]
multiplication:  [ 10  40  90 160 250]
division:  [0.1 0.1 0.1 0.1 0.1]


In [5]:
# universal functions
arr=np.array([2,3,4,5,6])

print(np.sqrt(arr))  # square root
print(np.exp(arr))  # exponential
print(np.sin(arr))  # sine
print(np.log(arr))  # natural log

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [11]:
# array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array\n",arr)
print(arr[0][0])
print(arr[0:2,2:])
print(arr[1:,2:])
print(arr[1:,1:3])

Array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[3 4]
 [7 8]]
[[ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]


In [13]:
#modify array elements
arr[0,0]=100
print(arr)
arr[1:]=100 #all the rows after 1st will be 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
